// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoadSafety.Web.Database;

#nullable disable

namespace RoadSafety.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260815145925_DevicesAndIncidents")]
    partial class DevicesAndIncidents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("RoadSafety.Web.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique();

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "KTW-CENTRAL",
                            CompanyId = 1,
                            Name = "Kitwe Central",
                            ReferenceNumber = "BR-001"
                        },
                        new
                        {
                            Id = 2,
                            Code = "WUSAKILE",
                            CompanyId = 1,
                            Name = "Wusakile",
                            ReferenceNumber = "BR-002"
                        },
                        new
                        {
                            Id = 3,
                            Code = "CHAMBOLI",
                            CompanyId = 1,
                            Name = "Chamboli",
                            ReferenceNumber = "BR-003"
                        },
                        new
                        {
                            Id = 4,
                            Code = "RTSA-KTW",
                            CompanyId = 2,
                            Name = "RTSA Kitwe Station",
                            ReferenceNumber = "BR-004"
                        });
                });

            modelBuilder.Entity("RoadSafety.Web.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique();

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ZPS",
                            Name = "Zambia Police Service",
                            ReferenceNumber = "CO-001",
                            RegistrationNumber = "ZPS-1965"
                        },
                        new
                        {
                            Id = 2,
                            Code = "RTSA",
                            Name = "Road Transport and Safety Agency",
                            ReferenceNumber = "CO-002",
                            RegistrationNumber = "RTSA-2002"
                        });
                });

            modelBuilder.Entity("RoadSafety.Web.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BranchReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleRegistration")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BranchReferenceNumber");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("RoadSafety.Web.Models.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BranchReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ImpactG")
                        .HasColumnType("REAL");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SpeedKph")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("BranchReferenceNumber", "OccurredAt");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("RoadSafety.Web.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanAssignRoles")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanManageOfficers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanManageRoles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SeesEveryBranch")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanAssignRoles = false,
                            CanManageOfficers = false,
                            CanManageRoles = false,
                            Description = "Reads their own station's records. Cannot add or change officers.",
                            IsBuiltIn = true,
                            Name = "Officer",
                            SeesEveryBranch = false
                        },
                        new
                        {
                            Id = 2,
                            CanAssignRoles = true,
                            CanManageOfficers = true,
                            CanManageRoles = false,
                            Description = "Adds, edits and removes the officers posted to their own station.",
                            IsBuiltIn = true,
                            Name = "Station administrator",
                            SeesEveryBranch = false
                        },
                        new
                        {
                            Id = 3,
                            CanAssignRoles = true,
                            CanManageOfficers = true,
                            CanManageRoles = true,
                            Description = "Manages every station, and the roles themselves.",
                            IsBuiltIn = true,
                            Name = "System administrator",
                            SeesEveryBranch = true
                        });
                });

            modelBuilder.Entity("RoadSafety.Web.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BranchReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ForceNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BranchReferenceNumber");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ForceNumber")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RoadSafety.Web.Models.Branch", b =>
                {
                    b.HasOne("RoadSafety.Web.Models.Company", "Company")
                        .WithMany("Branches")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RoadSafety.Web.Models.Device", b =>
                {
                    b.HasOne("RoadSafety.Web.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchReferenceNumber")
                        .HasPrincipalKey("ReferenceNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("RoadSafety.Web.Models.Incident", b =>
                {
                    b.HasOne("RoadSafety.Web.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchReferenceNumber")
                        .HasPrincipalKey("ReferenceNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoadSafety.Web.Models.Device", "Device")
                        .WithMany("Incidents")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("RoadSafety.Web.Models.User", b =>
                {
                    b.HasOne("RoadSafety.Web.Models.Branch", "Branch")
                        .WithMany("Users")
                        .HasForeignKey("BranchReferenceNumber")
                        .HasPrincipalKey("ReferenceNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoadSafety.Web.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RoadSafety.Web.Models.Branch", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("RoadSafety.Web.Models.Company", b =>
                {
                    b.Navigation("Branches");
                });

            modelBuilder.Entity("RoadSafety.Web.Models.Device", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("RoadSafety.Web.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
