// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoadSafety.Web.Database;

#nullable disable

namespace RoadSafety.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("RoadSafety.Web.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique();

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "KTW-CENTRAL",
                            CompanyId = 1,
                            Name = "Kitwe Central",
                            ReferenceNumber = "BR-001"
                        },
                        new
                        {
                            Id = 2,
                            Code = "WUSAKILE",
                            CompanyId = 1,
                            Name = "Wusakile",
                            ReferenceNumber = "BR-002"
                        },
                        new
                        {
                            Id = 3,
                            Code = "CHAMBOLI",
                            CompanyId = 1,
                            Name = "Chamboli",
                            ReferenceNumber = "BR-003"
                        },
                        new
                        {
                            Id = 4,
                            Code = "RTSA-KTW",
                            CompanyId = 2,
                            Name = "RTSA Kitwe Station",
                            ReferenceNumber = "BR-004"
                        });
                });

            modelBuilder.Entity("RoadSafety.Web.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique();

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ZPS",
                            Name = "Zambia Police Service",
                            ReferenceNumber = "CO-001",
                            RegistrationNumber = "ZPS-1965"
                        },
                        new
                        {
                            Id = 2,
                            Code = "RTSA",
                            Name = "Road Transport and Safety Agency",
                            ReferenceNumber = "CO-002",
                            RegistrationNumber = "RTSA-2002"
                        });
                });

            modelBuilder.Entity("RoadSafety.Web.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BranchReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ForceNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BranchReferenceNumber");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ForceNumber")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RoadSafety.Web.Models.Branch", b =>
                {
                    b.HasOne("RoadSafety.Web.Models.Company", "Company")
                        .WithMany("Branches")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RoadSafety.Web.Models.User", b =>
                {
                    b.HasOne("RoadSafety.Web.Models.Branch", "Branch")
                        .WithMany("Users")
                        .HasForeignKey("BranchReferenceNumber")
                        .HasPrincipalKey("ReferenceNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("RoadSafety.Web.Models.Branch", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("RoadSafety.Web.Models.Company", b =>
                {
                    b.Navigation("Branches");
                });
#pragma warning restore 612, 618
        }
    }
}
